source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
target :'ZZZiroom' do
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'Masonry'
pod 'BaiduMapKit'
pod 'FMDB'
pod 'TZImagePickerController'
end